services:
  ocr:
    image: ocr
    container_name: ocr-api
    build:
      context: .
      dockerfile: Dockerfile # Path to the Dockerfile which will be used to build the images
    depends_on:
      - postgres # Will force the postgres container to start before this one
    ports:
      - "8080:8080"
    volumes:
      - ./ocr_storage:/var/lib/ocr_storage
    environment:
      - DI_KEY=${DI_KEY}
      - DI_ENDPOINT=${DI_ENDPOINT}
      - OCR_STORAGE_PATH=/var/lib/ocr_storage
  postgres: # DNS resolves to this container name NOT the image or `container_name`
    image: postgres 
    container_name: ocr_postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ocr_db # Database name
