entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

certificatesResolvers:
  ocrresolver:
    acme:
      email: justin@eremos.cloud
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web
